name: ctdGeceGorus
version: 1.0.0
main: com.cletusthedigger.gecegorus.CtdGeceGorus
author: CletusTheDigger
description: Otomatik gece gorus plugini
commands:
  ctdgecegorus:
    description: Gece gorusunu ac/kapat
    usage: /ctdgecegorus <ac|kapat>
    aliases: [gecegorus, gg]
permissions:
  ctdgecegorus.admin:
    description: Plugin admin komutlarini kullanma yetkisi
    default: op
